[package]
name = "nimble-step-types"
version = "0.0.12-dev"
edition = "2021"
license = "MIT"
description = "Nimble Step Types"
repository = "https://github.com/nimble-rust/nimble"

[dependencies]
nimble-participant = { path = "../participant", version = "0.0.12-dev" }
seq-map = "^0.0.1"
