[package]
name = "nimble-step-types"
version = "0.0.11-dev"
edition = "2021"
license = "MIT"
description = "Nimble Step Types"
repository = "https://github.com/nimble-rust/nimble"

[dependencies]
nimble-participant = { path = "../participant", version = "0.0.11-dev" }
