[package]
name = "nimble-step-map"
version = "0.0.14-dev"
edition = "2021"
license = "MIT"
description = "Nimble Step Map"
repository = "https://github.com/nimble-rust/nimble"

[dependencies]
nimble-participant = { path = "../participant", version = "0.0.14-dev" }
seq-map = "0.0.2"
