[workspace]
members = [
    "crates/assent",
    "crates/client-logic",
    "crates/host",
    "crates/blob-stream",
    "crates/participant",
    "crates/participant-steps",
    "crates/steps",
    "crates/seer",
    "crates/rectify",
    "crates/protocol",
    "crates/ordered-datagram",
    "crates/datagram-pinger",
    "crates/sample-step",
    "crates/client",
    "crates/client-connecting",
    "crates/nimble",
    "crates/step-types", "crates/sample-game-type", "crates/client-front",
]
resolver = "2"
