[workspace]
members = [
    "crates/assent",
    "crates/client-logic",
    "crates/host-logic",
    "crates/blob-stream",
    "crates/participant",
    "crates/steps",
    "crates/seer",
    "crates/rectify",
    "crates/protocol",
    "crates/ordered-datagram",
    "crates/sample-step",
    "crates/client-stream",
    "crates/client-connecting",
    "crates/nimble",
    "crates/step-types",
    "crates/sample-game-type",
    "crates/client-front",
    "crates/protocol-header",
    "crates/client",
    "crates/host-stream",
    "crates/datagram-chunker",
    "crates/host-front",
    "crates/app-version",
]
resolver = "2"
