[package]
name = "nimble-client"
version = "0.0.12-dev"
edition = "2021"

[dependencies]
nimble-protocol = { path = "../protocol", version = "0.0.12-dev" }
nimble-client-front = { path = "../client-front", version = "0.0.12-dev" }
nimble-assent = { path = "../assent", version = "0.0.12-dev " }
nimble-seer = { path = "../seer", version = "0.0.12-dev" }
nimble-rectify = { path = "../rectify", version = "0.0.12-dev" }
nimble-step-types = { path = "../step-types", version = "0.0.12-dev" }
nimble-steps = { path = "../steps", version = "0.0.12-dev" }
flood-rs = "^0.0.11"
log = "0.4.22"
monotonic-time-rs = "^0.0.3"
metricator = "^0.0.2"

[dev-dependencies]
test-log = "^0.2.16"
nimble-sample-step = { path = "../sample-step", version = "0.0.12-dev" }
nimble-sample-game = { path = "../sample-game-type", version = "0.0.12-dev" }
