[package]
name = "nimble-client"
version = "0.0.12-dev"
edition = "2021"
license = "MIT"
description = "Nimble Client"
repository = "https://github.com/nimble-rust/client"

[dependencies]
log = "^0.4.22"
flood-rs = "^0.0.10"
nimble-client-logic = { path = "../client-logic", version = "0.0.12-dev" }
nimble-client-connecting = { path = "../client-connecting", version = "0.0.12-dev" }
nimble-ordered-datagram = { path = "../ordered-datagram", version = "0.0.12-dev" }
datagram-pinger = { path = "../datagram-pinger", version = "0.0.12-dev" }
datagram = "^0.0.2"
nimble-protocol = { path = "../protocol", version = "0.0.12-dev" }
nimble-step-types = { path = "../step-types", version = "0.0.12-dev" }
datagram-builder = "^0.0.2"
hexify = "^0.0.1"

[dev-dependencies]
nimble-sample-step = { path = "../sample-step", version = "0.0.12-dev" }
nimble-steps = { path = "../steps", version = "0.0.12-dev" }
test-log = "0.2.16"
