[package]
name = "nimble-client"
version = "0.0.12-dev"
edition = "2021"

[dependencies]
nimble-protocol = { path = "../protocol", version = "0.0.12-dev" }
nimble-client-front = { path = "../client-front", version = "0.0.12-dev" }
nimble-assent = { path = "../assent", version = "0.0.12-dev " }
nimble-seer = { path = "../seer", version = "0.0.12-dev" }
nimble-rectify = { path = "../rectify", version = "0.0.12-dev" }
nimble-step-types = { path = "../step-types", version = "0.0.12-dev" }
nimble-steps = { path = "../steps", version = "0.0.12-dev" }
flood-rs = "0.0.11"
log = "0.4.22"
monotonic-time-rs = "0.0.3"
metricator = "0.0.2"
app-version = "0.0.2"
tick-id = "0.0.7"
err-rs = "0.0.2"

[dev-dependencies]
test-log = "0.2.16"
nimble-sample-step = { path = "../sample-step", version = "0.0.12-dev" }
nimble-sample-game = { path = "../sample-game-type", version = "0.0.12-dev" }
nimble-host-stream = { path = "../host-stream", version = "0.0.12-dev" }
nimble-host-front = { path = "../host-front", version = "0.0.12-dev" }
nimble-host-logic = { path = "../host-logic", version = "0.0.12-dev" }
tick-id = "0.0.7"
hazy-transport = "0.0.3"
rand = "0.8.5"
seq-map = "0.0.1"
nimble-participant = { path = "../participant", version = "0.0.12-dev" }