[package]
name = "datagram-pinger"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "Datagram latency library"
repository = "https://github.com/nimble-rust/nimble"

[dependencies]
flood-rs = "^0.0.10"
