[package]
name = "nimble-rust"
version = "0.0.10-dev"
edition = "2021"
license = "MIT"
description = "Nimble"
repository = "https://github.com/nimble-rust/nimble"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nimble-client = { path = "../client", version = "0.0.10-dev" }
nimble-host = { path = "../host", version = "0.0.10-dev" }
nimble-assent = { path = "../assent", version = "0.0.10-dev" }
nimble-seer = { path = "../seer", version = "0.0.10-dev" }
nimble-rectify = { path = "../rectify", version = "0.0.10-dev" }
flood-rs = "^0.0.10"
nimble-steps = { path = "../steps", version = "0.0.10-dev" }
tick-id = "^0.0.7"
nimble-protocol = { path = "../protocol", version = "0.0.10-dev" }
nimble-sample-step = { path = "../sample-step", version = "0.0.10-dev" }
nimble-client-logic = { path = "../client-logic", version = "0.0.10-dev" }
log = "^0.4.22"
nimble-step-types = { path = "../nimble-step-types", version = "0.0.10-dev" }

[dev-dependencies]
test-log = "^0.2.16"


[package.metadata.cargo-machete]
ignored = ["nimble_client"]
[package.metadata.cargo-shear]
ignored = ["nimble-client"]
