[package]
name = "nimble-step"
version = "0.0.16"
edition = "2021"
license = "MIT"
description = "Nimble Step"
repository = "https://github.com/nimble-rust/nimble"
categories = ["game-development"]
keywords = ["game", "network"]

[dependencies]
tick-id = "0.0.9"
flood-rs = "0.0.12"
