on: [ push ]

name: Rust Build

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - run: RUSTFLAGS="-D warnings" cargo clippy --color=always # -- -Wclippy::pedantic
      - run: RUSTFLAGS="-D warnings" cargo build --color=always --all-features
      - name: run tests with color multiple times
        env:
          RUST_LOG: trace
          RUST_LOG_STYLE: always
          TERM: xterm-256color
        run: |
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always
          cargo test --color=always -- --nocapture --color=always
      - run: rustup install nightly

      # - run: cargo +nightly update -Zminimal-versions
      # - run: cargo +nightly test

      - run: cargo +nightly update -Zdirect-minimal-versions
      - run: cargo +nightly test

      - run: cargo install cargo-llvm-cov
      - run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
